version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: dogwalker_backend
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_URL=$MONGO_USERNAME
      - SECRET_KEY=$SECRET_KEY
      - WEB_PORT=$WEB_PORT